# Conditional and Slice Selection

In [3]:
import numpy as np

In [5]:
arr = np.arange(0,9)

In [6]:
arr = arr.reshape(3,3)

In [8]:
up_to_five = arr < 6
up_to_five

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]], dtype=bool)

In [9]:
arr[up_to_five]

array([0, 1, 2, 3, 4, 5])

In [10]:
# it's equivalent to the above but in one go
arr[arr < 6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr = np.arange(40).reshape(8,5)

In [12]:
# any boolean operation applicable to the datatype contained in the array
arr[arr % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [15]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [17]:
# slice notation to get an internal sub matrix
arr[1:5, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [18]:
arr[:3,3:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])