# Numpy Arrays

In [1]:
import numpy as np

In [2]:
# similar to range, takes the minimum inclusive and goes to the maximum exclusive
# advancing by the defined steps
np.arange(0,11,.5)

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5])

In [3]:
# fills a zero vector with n elements
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [4]:
# fills a nxm matrix with zero's
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [5]:
# fills a nxm matrix with one's
# works for any dimension
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
# fills a vector with equally sized n 'chunks' from the minimum(inclusive) to maximum(inclusive)
np.linspace(0,10,10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [7]:
# fills an n elements squared identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
# fills the specified shape with random values
np.random.rand(5)

array([ 0.96394961,  0.21122117,  0.81700644,  0.17082207,  0.0559106 ])

In [9]:
# can be used to fill a matrix, noting that it takes
np.random.rand(3,3)

array([[ 0.98016388,  0.46198136,  0.11956787],
       [ 0.04048452,  0.23777006,  0.18931829],
       [ 0.05477132,  0.25276519,  0.72319139]])

In [10]:
# fills shape
np.random.randn(5)

array([ 2.93696882,  0.70292155,  1.52997728, -0.89723214,  1.62411772])

In [34]:
# get a random int 
np.random.randint(4)

3

In [12]:
# using a minimum and maximum inclusive
np.random.randint(1,100,5)

array([30, 81, 97, 44, 30])

In [13]:
my_array = np.arange(9)

In [14]:
# transform the shape of the array must use all the elements NOTE: array.lenght = n*m*o...
my_array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
another_array = np.arange(15)

In [16]:
# as specified in the definition it doesn't need to be a square
another_array.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
another_array.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
# can be done to reduce dimensions or "unwrap" the matrix
another_array.reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# checking that if it doesn't use all the elements it won't reshape
another_array.reshape(2,7)

ValueError: cannot reshape array of size 15 into shape (2,7)

In [20]:
# can be used like this as well
another_array.reshape(1,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [22]:
randomized_array = np.random.randint(1,100,9)
randomized_array

array([42, 32, 16, 58, 16, 89, 10, 77, 30])

In [23]:
# can get the minimum value
randomized_array.min()

10

In [24]:
# maximum as well
randomized_array.max()

89

In [25]:
# get the index of the maximum value
# .argmin() works for the minimum
randomized_array.argmax()

5

In [26]:
# you can get the mean 
randomized_array.mean()

41.111111111111114

In [28]:
square_matrix = randomized_array.reshape(3,3)

In [29]:
# can always see the shape of the array
square_matrix.shape

(3, 3)

In [30]:
square_matrix.reshape(1,9)

array([[42, 32, 16, 58, 16, 89, 10, 77, 30]])